### PR TITLE
Bridge Integration with Storj/Core

### LINKED ISSUE #188: Integrate node-storj as backend in place of python implementation

### PR DESCRIPTION
**Pull request by gordonwritescode**
* Remove dataserv installer/updater
* Remove dataserv wrapper
* Integrate with node-storj
* License changed to satisfy node-storj GPL
* Replace locked form with log output when drive is running
* Add telemetry reporter with dismissible warning when enabled

Closes #188

### Screenshots

screenshot-20160331-16 56 04

screenshot-20160331-16 56 16

screenshot-20160401-14 20 30

### CODE REVIEW

**Comment by gordonwritescode** [comment]
@littleskunk - whenever you have some time to test this out :)

**Comment by super3** [comment]
@gordonwritescode Probably add that telemetry is required to receive beta rewards during the beta testing.

**Comment by littleskunk** [comment]
I have some good and some bad news. Lets start with the good news:

Driveshare-GUI + node-storj are running. No problems with my old config file. Looks good to me.

Now the bad news.
1.) Telemetry data warning dismiss should be stored in the config file. I get the message every time I quit and start driveshare-gui again. (low prio)
2.) The option send telemetry reports is default true if a new config is generated but if I use my old 0.5.1 config it is default false. (low prio)
3.) Telemetry data is overlapping. See screenshot (appveyor windows binary) (low prio)
screenshot
4.) I don't see any telemetry data I could verify. User will ask for reported values. At least a log entry would be nice. (medium prio)
5.) Missmatch between documentation, driveshare-gui and statusify implementation.
documentation: https://github.com/Storj/driveshare-gui/issues/193#issuecomment-204431005
driveshare-gui (timestamp missing): https://github.com/Storj/driveshare-gui/blob/a7e224f8ccf5770134a709f6052fb3341650fcbe/app/lib/telemetry.js#L33-L82
I am not sure the 
statusify (old version, store renamed in storage): https://github.com/Storj/statusify/blob/397d58bb207f1fcacc87b96082cee851908f56ef/app/models/report.js#L4-L261

Not part of this pull request but needed for a stable 0.6.0 release:
Issue 190 (windows launch at user login)
Issue 180 (large memory usage and later out of memory exception)

Not complete implemented:
Bandwidth test is missing. Hardcoded values for the report.
I see no encryption. It looks like a plain post message + signature to me.

**Comment by gordonwritescode** [comment]
Working on these:

* [ ] Telemetry data warning dismiss should be stored in the config file. I get the message every time I quit and start driveshare-gui again. (low prio)
* [x] The option send telemetry reports is default true if a new config is generated but if I use my old 0.5.1 config it is default false. (low prio)
* [ ] Telemetry data is overlapping. See screenshot (appveyor windows binary) (low prio)
screenshot
* [ ] I don't see any telemetry data I could verify. User will ask for reported values. At least a log entry would be nice. (medium prio)
* [x] ~~Missmatch between documentation, driveshare-gui and statusify implementation. documentation: #193 (comment)~~ - moved to [Storj/farmer](https://github.com/storj/farmer)
* [ ] Bandwidth test is missing. Hardcoded values for the report.
* [x] ~~I see no encryption. It looks like a plain post message + signature to me.~~ - moved to [Storj/farmer](https://github.com/storj/farmer)

**Comment by gordonwritescode** [comment]
Okay, this is *almost* ready to go. Just need to spin up the speedtest service and add the URL to the config.

**Comment by littleskunk** [comment]
Windows binary is not working. See screenshot:
screenshot

5 days ago the windows binary was working. It looks like the reason has something to do with the repository renaming but I can't find any mistake.

Both folder exists after binary installation:
C:\Program Files (x86)\StorjFarmer\resources\app\node_modules\storj
C:\Program Files (x86)\StorjFarmer\resources\app\node_modules\storj-farmer

I don't find any storj-farmer/nodemodules

**Comment by littleskunk** [comment]
Fixed the first error but now I have got a new problem. 

Here is what I have done:
Nodejs5 (like the current appveyor file) is not working.
Nodejs4 is working as long as npm 2 is installed. Update to latest npm2 is possible. Update to npm3 and you are screwed.

Now back to the new problem:
is-property is missing. It should be here but there is only an empty folder:
`C:\Program Files (x86)\StorjFarmer\resources\app\node_modules\storj-farmer\node_modules\storj\node_modules\localtunnel\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\node_modules`

**Comment by littleskunk** [comment]
The node modul folder structure is different between npm2 and npm3. npm2 creates subfolder inside a package for the dependenies. 5 days ago driveshare-gui includes node-storj. Now farmer-gui includes storj-farmer and that includes storj (core). One more folder and now we have funn with windows path lenght limit. npm install had no problem with that limit but NSIS is unable to create a binary.

I did everything I could. The unicode version of NSIS is not working as well. I see only one last change. npm3 creates one node modul folder in the app root directory. That is fine for NSIS but at the moment farmer-gui create 2 node module folder. `/node_modules` and `/app/node_modules`. npm start will use one of them and the module of the other folder are missing.

New plan: get npm3 running. Your last commit 24ffb3360b933d7997e5274ba084a659691baa91fixed one error message but get more and this is the reason: https://github.com/Storj/farmer/blob/4a0a5d31eeb62402167b58d16a368372b6a64474/lib/telemetry.js#L6-L8

**Comment by gordonwritescode** [comment]
@littleskunk give the build another go whenever you get a chance - i'm hoping these changes fix it

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 805c29cfbf8b43470247bcc7d0d014ac44f2e1b5
[storj-farmer-gui_0.6.0.osx64.dmg](https://github.com/Storj/farmer-gui/releases/download/untagged-75103321d19fc1b55d5e/storj-farmer-gui_0.6.0.osx64.dmg)

**Comment by gordonwritescode** [comment]
WOoOoOoOoOoOoOoOoOoOo!

**Pull request merged**
