### PR TITLE
new tray icons

### PR DESCRIPTION
**Pull request by littleskunk**
https://github.com/Storj/farmer-gui/issues/161

@boshevski autobin binaries will follow in some minutes. Please review them. I assume windows and linux are fine but a black osx icon? That looks strange.

You can update the branch if needed. As long as the pull request is open autobin will build new binaries.

### CODE REVIEW

**Comment by boshevski** [comment]
OSX icon looks great!

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 7746a9e45f262ba83a58963a16c99d6267458df6
[storjshare-gui.win32.exe](https://github.com/Storj/farmer-gui/releases/download/untagged-c991113dcf36654078d9/storjshare-gui.win32.exe)

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 9bc503c1bb3bbe74fe9603fd137aa2dd17b9e77a
[storjshare-gui.osx64.dmg](https://github.com/Storj/farmer-gui/releases/download/untagged-c991113dcf36654078d9/storjshare-gui.osx64.dmg)

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 9149ede4b145e922f0bd014c02a9c9fa3f98e16b
[storjshare-gui.amd64.deb](https://github.com/Storj/farmer-gui/releases/download/untagged-c991113dcf36654078d9/storjshare-gui.amd64.deb)
[storjshare-gui.osx64.dmg](https://github.com/Storj/farmer-gui/releases/download/untagged-c991113dcf36654078d9/storjshare-gui.osx64.dmg)

**Pull request merged**
